# Generated by Django 5.0.6 on 2026-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('otp_requested', 'OTP requested'), ('otp_request_rate_limited', 'OTP request rate limited'), ('otp_verify_succeeded', 'OTP verify succeeded'), ('otp_verify_failed', 'OTP verify failed'), ('otp_verify_locked', 'OTP verify locked out')], db_index=True, max_length=64)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='audit_audit_email_e25057_idx'), models.Index(fields=['event', '-created_at'], name='audit_audit_event_b448e9_idx')],
            },
        ),
    ]
